title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
theme: minima
  With this project, we aim to apply in-depth research, 
  GIS mapping technology, and direct engagement with 
  neighborhood renters, homeowners, and property owners 
  to better understand the current landscape of Whittier’s
  NOAH stock and identify individual properties that may be 
  vulnerable to sale. This will provide the fact basis for a 
  strategic effort to connect with community-minded owners on 
  creative approaches to extend affordability and combat displacement, 
  as prioritized in the Whittier Alliance’s 5-year plan.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
